name: wrangler

on: [push]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo fmt --all --check

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo check

  deploy-to-production:
    name: deploy
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    environment: 
      name: Production
      url: https://images-proxy.fables.workers.dev
    steps:
      - uses: actions/checkout@v2
      - uses: ker0olos/wrangler-action@79ab8d9ea54478069c2afe2bcaaa475514c9638d
        name: Deploy to Cloudflare Workers
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish --env production

  deploy-to-preview:
    name: deploy
    runs-on: ubuntu-latest
    if: github.ref_name != 'main'
    environment: 
      name: Preview
      url: https://images-proxy-preview.fables.workers.dev
    steps:
      - uses: actions/checkout@v2
      - uses: ker0olos/wrangler-action@79ab8d9ea54478069c2afe2bcaaa475514c9638d
        name: Deploy to Cloudflare Workers
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish --env preview